import { Montserrat } from "next/font/google";
import "./globals.css";

import styles from "../app/page.module.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      <body className={`${montserrat.variable} `} suppressHydrationWarning>
        {children}
        <footer className={styles.footer}>
          <div className={styles.container}>
            <p>&copy; 2025 - Dev Assina - Todos os direitos reservados.</p>
          </div>
          <div>
            <a href="https://land1.abxyz.info/policy_gdpr/-7EBRQCgQAAAEBAzqWA0ioNyWIAfoHAAMPpX7VZxERChEJIhENQhENWgdubDIAAH9hZGNvbWJv_zduanRGdGpuAANlOA">
              Privacy policy
            </a>
            <a href="https://ac-feedback.com/report_form/">report</a>
          </div>
        </footer>
      </body>
    </html>
  );
}
